const products=[
 {id:1,name:'The Second Skin Bralette',type:'Bras',price:1890,color:'#d38770',bg:'#ead2bd',art:'bra',colors:['#d38770','#1d2926','#e8dbcc']},
 {id:2,name:'The Cloud Brief',type:'Briefs',price:990,color:'#afbdab',bg:'#dfe6dc',art:'brief',colors:['#afbdab','#ded7cc','#3f5148']},
 {id:3,name:'The Everyday Set',type:'Sets',price:2790,color:'#c47d68',bg:'#e8c9b6',art:'set',colors:['#c47d68','#d9b6a0','#6d7c70']},
 {id:4,name:'The Barely There Thong',type:'Briefs',price:890,color:'#d2a951',bg:'#f0dfbd',art:'brief',colors:['#d2a951','#e4c2ad','#d7ddcf']},
 {id:5,name:'The Soft Cup Bra',type:'Bras',price:2190,color:'#809889',bg:'#d5ddd2',art:'bra',colors:['#809889','#d8c7bb','#3d4f47']},
 {id:6,name:'The Sunday Set',type:'Sets',price:3190,color:'#d9ac9b',bg:'#f0d9cf',art:'set',colors:['#d9ac9b','#b1c0b4','#eee6d8']},
 {id:7,name:'The High Rise Brief',type:'Briefs',price:1090,color:'#697c72',bg:'#d9e1db',art:'brief',colors:['#697c72','#d4a38e','#ece7dd']},
 {id:8,name:'The Sculpting Bra',type:'Bras',price:2490,color:'#455a50',bg:'#ccd6cf',art:'bra',colors:['#455a50','#d0a793','#efe2d5']}
];
let active='All',cart=JSON.parse(localStorage.getItem('libani-cart')||'[]');
const grid=document.querySelector('#product-grid'),count=document.querySelector('#product-count');
function art(p){return `<div class="item-art art-${p.art}" style="--item:${p.color};--item-bg:${p.bg}"></div>`}
function money(value){return `â‚¹${value.toLocaleString('en-IN')}`}function renderProducts(){const shown=active==='All'?products:products.filter(p=>p.type===active);count.textContent=`${shown.length} PIECES`;grid.innerHTML=shown.map(p=>`<article class="product-card" data-product="${p.id}"><div class="product-image" style="background:${p.bg}">${art(p)}<button class="add" data-id="${p.id}" aria-label="Add ${p.name} to bag">+</button></div><div class="product-info"><h3>${p.name}</h3><div class="product-meta"><span>${p.type}</span><strong>${money(p.price)}</strong></div><div class="swatches">${p.colors.map(c=>`<i class="swatch" style="background:${c}"></i>`).join('')}</div></div></article>`).join('')}
function save(){localStorage.setItem('libani-cart',JSON.stringify(cart))}
function renderCart(){const total=cart.reduce((sum,item)=>sum+item.price*item.qty,0),qty=cart.reduce((sum,item)=>sum+item.qty,0);document.querySelector('#bag-count').textContent=qty;document.querySelector('#cart-title-count').textContent=`(${qty})`;document.querySelector('#subtotal').textContent=`$${total.toFixed(2)}`;const box=document.querySelector('#cart-items');if(!cart.length){box.innerHTML=`<div class="empty-cart"><span>â—Œ</span><p>Your bag is feeling a little light.</p><button class="text-link close-cart">Keep shopping â†’</button></div>`;return}box.innerHTML=cart.map(item=>`<div class="cart-item"><div class="cart-item-art" style="background:${item.bg}">${art(item)}</div><div><h3>${item.name}</h3><p>${item.type} Â· ${item.colorName||'Sand'}</p><strong>$${item.price}</strong><div class="qty"><button data-action="minus" data-id="${item.id}">âˆ’</button><span>${item.qty}</span><button data-action="plus" data-id="${item.id}">+</button></div></div><button class="remove" data-action="remove" data-id="${item.id}" aria-label="Remove ${item.name}">Ã—</button></div>`).join('')}
function toast(text){const t=document.querySelector('.toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function toggleCart(open){document.querySelector('.cart-panel').classList.toggle('open',open);document.querySelector('.overlay').classList.toggle('show',open);document.querySelector('.cart-panel').setAttribute('aria-hidden',!open)}
document.addEventListener('click',e=>{const add=e.target.closest('.add');if(add){const p=products.find(x=>x.id===+add.dataset.id),existing=cart.find(x=>x.id===p.id);existing?existing.qty++:cart.push({...p,qty:1});save();renderCart();toast(`${p.name} added to your bag`)}const filter=e.target.closest('.filter');if(filter){active=filter.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===filter));renderProducts()}const cat=e.target.closest('.category');if(cat){active=cat.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===active));setTimeout(renderProducts,0)}if(e.target.closest('.bag-button'))toggleCart(true);if(e.target.closest('.close-cart')||e.target.matches('.overlay'))toggleCart(false);const action=e.target.dataset.action;if(action){const item=cart.find(x=>x.id===+e.target.dataset.id);if(action==='plus')item.qty++;if(action==='minus'){item.qty--;if(item.qty===0)cart=cart.filter(x=>x.id!==item.id)}if(action==='remove')cart=cart.filter(x=>x.id!==item.id);save();renderCart()}if(e.target.closest('#checkout')){if(!cart.length)toast('Your bag is empty');else{cart=[];save();renderCart();toggleCart(false);toast('Order placed â€” thank you!')}}if(e.target.closest('#fit-finder'))toast('Based on your answers, weâ€™ll recommend a medium-support bra.')});
document.querySelector('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();e.target.reset();document.querySelector('#newsletter-message').textContent='Youâ€™re on the list â€” welcome to Libani.'});
function openProduct(id){const p=products.find(x=>x.id===id),modal=document.querySelector('.product-modal');document.querySelector('#modal-art').style.background=p.bg;document.querySelector('#modal-art').innerHTML=art(p);document.querySelector('#modal-type').textContent=p.type.toUpperCase();document.querySelector('#modal-name').textContent=p.name;document.querySelector('#modal-price').textContent=money(p.price);document.querySelector('#modal-swatches').innerHTML=p.colors.map((c,i)=>`<i class="swatch ${i===0?'active':''}" style="background:${c}" data-colour="${c}"></i>`).join('');document.querySelector('#modal-add').dataset.id=p.id;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeProduct(){const modal=document.querySelector('.product-modal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.addEventListener('click',e=>{const card=e.target.closest('.product-card');if(card&&!e.target.closest('.add'))openProduct(+card.dataset.product);if(e.target.closest('.modal-close'))closeProduct();const size=e.target.closest('.size-options button');if(size){document.querySelectorAll('.size-options button').forEach(b=>b.classList.toggle('selected',b===size))}const modalAdd=e.target.closest('#modal-add');if(modalAdd){const p=products.find(x=>x.id===+modalAdd.dataset.id),existing=cart.find(x=>x.id===p.id);existing?existing.qty++:cart.push({...p,qty:1});save();renderCart();closeProduct();toast(`${p.name} added to your bag`)}});
renderProducts();renderCart();

